export type UserRole = 'admin' | 'petani';

export interface Petani {
  id: string;
  nama: string;
  nik: string;
  noHp: string;
  blokLahan: string;
  luasHa: number;
  jmlPokok: number;
  noRekening: string;
  bank: string;
  statusAktif: boolean;
  tanggalGabung: string;
  fotoUrl?: string;
}

export interface ArmadaTruk {
  id: string;
  platNomor: string;        // Contoh: BM 8412 TA
  namaSopir: string;        // Contoh: Pak Eko
  noHpSopir?: string;       // Contoh: 0812-7654-3210
  jenisKendaraan: string;   // Contoh: Colt Diesel Canter (6 Roda), Dump Truk, Fuso
  kapasitasTon: number;     // Contoh: 8.5 (Ton)
  pksLangganan?: string;    // Contoh: PKS PT. Sawit Sejahtera
  status: 'Aktif' | 'Perbaikan' | 'Nonaktif';
  catatan?: string;
}

export interface PanenRecord {
  id: string;
  noSpb: string; // Surat Pengantar Buah
  tanggal: string;
  petaniId: string;
  petaniNama: string;
  blokLahan: string;
  
  // Tonase
  timbanganRamKg: number;    // Berat timbangan kebun / ram luar
  timbanganPksKg: number;    // Berat netto timbangan pabrik
  selisihKg: number;         // timbanganRamKg - timbanganPksKg (penyusutan)
  persentaseSelisih: number; // (selisihKg / timbanganRamKg) * 100
  
  // Harga & Bruto
  hargaTbsPerKg: number;     // Rp/Kg
  totalBruto: number;        // timbanganPksKg * hargaTbsPerKg
  
  // Potongan / Pedaran
  potonganPedaranKg: number;     // Potongan sortasi / sampah / tangkai panjang
  potonganPedaranRupiah: number; // potonganPedaranKg * hargaTbsPerKg
  potonganIuranKasRupiah: number;// Misal Rp 25/kg dari timbangan PKS
  upahPemanenRupiah: number;     // Misal Rp 180/kg
  kasbonPupukRupiah: number;     // Potongan angsuran kasbon/pupuk
  totalPotongan: number;         // Total seluruh potongan
  
  // Netto Petani (Timbangan Kebun × Harga TBS)
  totalNetto: number;            // (timbanganRamKg || timbanganPksKg) * hargaTbsPerKg
  
  // Info Logistik & PKS
  namaPks: string;               // Contoh: PKS PT. Sawit Sejahtera, PKS Agro Mandiri
  platTruk: string;              // BM 8412 TA
  namaSopir: string;
  namaPemanen: string;
  
  // Status
  statusPembayaran: 'Lunas' | 'Siap Bayar' | 'Draft';
  tanggalBayar?: string;
  metodeBayar?: 'Transfer Bank' | 'Tunai / Kas';
  catatan?: string;
}

export interface KasKelompok {
  id: string;
  tanggal: string;
  jenis: 'Masuk' | 'Keluar';
  kategori: 'Iuran Panen' | 'Iuran Bulanan' | 'Medaran' | 'Selisih Timbangan / Margin Panen' | 'Penjualan Pupuk' | 'Perawatan Jalan Kebun' | 'Operasional Pengurus' | 'Sosial & Santunan' | 'Lainnya';
  keterangan: string;
  jumlah: number;
  saldoSetelah: number;
  buktiRef?: string;
  petaniNamaTerkait?: string;
  panenId?: string;
  isAutoGenerated?: boolean;
}

export interface PinjamanKasbon {
  id: string;
  petaniId: string;
  petaniNama: string;
  tanggalPinjam: string;
  keperluan: 'Pupuk NPK & Urea' | 'Bibit Sawit Unggul' | 'Herbisida / Racun' | 'Kebutuhan Mendesak' | 'Alat Egrek / Dodos';
  jumlahPinjaman: number;
  sisaPinjaman: number;
  potonganPerPanen: number;
  status: 'Aktif' | 'Lunas';
  keterangan: string;
}

export interface PengaturanKelompok {
  namaKelompok: string;
  badanHukum: string;
  legalitasNo?: string;
  alamatLengkap: string;
  alamat?: string;
  desa: string;
  kecamatan: string;
  kabupaten: string;
  provinsi: string;
  kodePos?: string;
  noKontak: string;
  kontakPengurus?: string;
  ketua: string;
  namaKetua?: string;
  bendahara: string;
  namaBendahara?: string;
  sekretaris: string;
  namaPksDefault?: string;
  hargaTbsDefault: number;
  tanggalPanenDefault?: string;
  tarifIuranKasPerKg: number;
  potonganIuranKasPerKg?: number;
  tarifUpahPanenPerKg: number;
  upahPemanenPerKg?: number;
  tarifLangsirPerKg: number;
  biayaPedaranPerKg?: number;
  toleransiSusutPersen: number;
  rekeningKasUtama: string;
  bankKasUtama: string;
}

export interface DatabaseBackupData {
  app?: string;
  version?: string;
  exportedAt?: string;
  pengaturan?: PengaturanKelompok;
  petaniList?: Petani[];
  armadaList?: ArmadaTruk[];
  panenList?: PanenRecord[];
  kasList?: KasKelompok[];
  pinjamanList?: PinjamanKasbon[];
}

export type ActiveTab = 
  | 'dashboard' 
  | 'armada'
  | 'panen' 
  | 'rekap' 
  | 'selisih' 
  | 'kas' 
  | 'petani' 
  | 'cetak-laporan' 
  | 'asisten-ai' 
  | 'pengaturan';
